###

GET http://localhost:3000/usuarios

###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "João",
    "email": "joao@email.com",
    "senha": "123"
}

###

PUT http://localhost:3000/usuarios/1
Content-Type: application/json

{
    "nome": "Gairo",
    "email": "gairo@email.com",
    "senha": "Fire red"
}

###

DELETE http://localhost:3000/usuarios/

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "joao@email.com",
    "senha": "123"
}